In [1]:
import numpy as np

In [2]:
# Exericicio 1
ones = np.ones(8)
aleatorio = np.random.randint(0,10,8)

soma = ones + aleatorio
print(ones)
print(aleatorio)
print(soma)



[1. 1. 1. 1. 1. 1. 1. 1.]
[2 9 9 7 2 9 9 2]
[ 3. 10. 10.  8.  3. 10. 10.  3.]


In [3]:
if sum(soma) >= 40:
    soma = soma.reshape(4,2)
else:
    soma = soma.reshape(2,4)

print(soma)

[[ 3. 10.]
 [10.  8.]
 [ 3. 10.]
 [10.  3.]]


In [4]:
# Exercicio 2
pares1 = np.arange(0,51,2)
pares2 = np.arange(100,49,-2)

array = np.concatenate((pares1, pares2))
array.sort() # ordenando o array
print(array)



[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  50  52  54  56  58  60  62  64  66  68
  70  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [5]:
# Exercicio 3 - Campo minado
from random import randint
import numpy as np


matriz = np.zeros((2,2))

number_linha = randint(0,1)
number_coluna = randint(0,1)

matriz[number_linha][number_coluna] = 1

print('bomba na posição: ', number_linha, number_coluna)

jogadas = 3
acertos = 0

while jogadas > 0:
    print("Selecione um posição da matriz: ")
    linha = int(input("Entre com a linha ( 0 ou 1): "))
    coluna = int(input("Entre com a coluna ( 0 ou 1): "))
    
    if matriz[linha][coluna] == 0:
        print("Correto acertou uma posição!".center(50,'-'))
        matriz[linha][coluna] = 2 # local descoberto
        
        acertos += 1
        if acertos == 3:
            print("Congratulations! You beat the game!")
            break
        
    elif matriz[linha][coluna] == 2:
        print("posição já escolhida")
        continue
    
    else:
        print("Game Over! :( Try Again! ")
        break   
        
    jogadas -= 1
            
    
    
    
    

bomba na posição:  1 1
Selecione um posição da matriz: 
Game Over! :( Try Again! 


In [6]:
# Exercicio 4
l = randint(2,6)
c = randint(2,6)
print(l)
print(c)

m = np.random.randint(0,10,(l,c))

print(m)

produto = l * c
print(produto)

if produto % 2 == 0: # valor par é possivel virar um array
    print("Pode virar um array 1D")
else:
    print("Não pode virar um array 1D")
    

2
3
[[3 5 8]
 [8 4 9]]
6
Pode virar um array 1D


In [7]:
# Exercicio 5
# semente aleatoria
np.random.seed(10)
matriz = np.random.randint(1,51, (4,4))
print(matriz)

[[10 37 16  1]
 [50 29 26 30]
 [49 30 50  9]
 [10  1 43 41]]


In [8]:
media_linha = matriz.mean(axis=1)
media_coluna = matriz.mean(axis=0)
print("Media de cada linha: ", media_linha)
print("Media de cada coluna: ", media_coluna)


Media de cada linha:  [16.   33.75 34.5  23.75]
Media de cada coluna:  [29.75 24.25 33.75 20.25]


In [9]:
print("Maior media das linhas: ", media_linha.max())
print("Maior media das colunas: ", media_coluna.max())


Maior media das linhas:  34.5
Maior media das colunas:  33.75


In [10]:
numeros_unicos, contagem = np.unique(matriz, return_counts=True)

for number, cont  in zip(numeros_unicos, contagem):
    print(f"O numero {number} aparece {cont}")
    

O numero 1 aparece 2
O numero 9 aparece 1
O numero 10 aparece 2
O numero 16 aparece 1
O numero 26 aparece 1
O numero 29 aparece 1
O numero 30 aparece 2
O numero 37 aparece 1
O numero 41 aparece 1
O numero 43 aparece 1
O numero 49 aparece 1
O numero 50 aparece 2


In [11]:
# Numeros que aparecem 2 vezes na matriz
print(numeros_unicos[contagem == 2])

[ 1 10 30 50]


In [12]:
# Atividade 3

df = np.loadtxt('/home/nkk/Área de trabalho/projetos/C11/space.csv', delimiter=';', dtype=str, encoding='utf-8')


In [13]:
# 1 porcentagem de missos bem sucedidas

df[1:,7]



array(['Success', 'Success', 'Success', ..., 'Failure', 'Success',
       'Success'], shape=(4324,), dtype='<U84')