In [2]:
import numpy as np

In [6]:
arr1 = np.array([1,2,3], dtype=np.int16)
print(arr1)
print(type(arr1))
print(type(arr1[0]))

[1 2 3]
<class 'numpy.ndarray'>
<class 'numpy.int16'>


In [15]:
arr2d = np.array([[-4,2,3],[4,5,6]])
arr2d

array([[-4,  2,  3],
       [ 4,  5,  6]])

In [16]:
print(arr2d.min(), arr2d.argmin())

-4 0


In [17]:
print(arr2d.max(), arr2d.argmax())

6 5


In [18]:
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
# transformar para matriz
zeros_matriz = np.zeros(10).reshape(5,2)
zeros_matriz

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [29]:
a = np.ones([3,3], dtype=np.int16)
b = np.arange(85,101)
print(a)
print(b)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[ 85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100]


In [35]:
c = np.arange(1,10,1)
d = np.arange(9,0,-1)
print(c)
print(d)
print(c + d*2)


[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]
[19 18 17 16 15 14 13 12 11]


In [43]:
print(np.concatenate((c,d)))


[1 2 3 4 5 6 7 8 9 9 8 7 6 5 4 3 2 1]


In [ ]:
matriz = np.array([50,10,100,60,25,100,75,80,100]).reshape(3,3) # agua luz net
matriz

array([[ 50,  10, 100],
       [ 60,  25, 100],
       [ 75,  80, 100]])

In [50]:
print("Valor total das contas no mes: ", matriz.sum(1)) 
print("Valor total nos tres meses por tipo: ", matriz.sum(0))
print("Valor gasto de net no período: ", matriz.sum(0)[2])

Valor total das contas no mes:  [160 185 255]
Valor total nos tres meses por tipo:  [185 115 300]
Valor gasto de net no período:  300


In [53]:
# Broadcasting 
print('Matriz dividido por 2: ', matriz/2)
print("Matriz multiplicado por 2: ", matriz*2)
print("Matriz com 10% de desconto: ", matriz * 0.9)

Matriz dividido por 2:  [[25.   5.  50. ]
 [30.  12.5 50. ]
 [37.5 40.  50. ]]
Matriz multiplicado por 2:  [[100  20 200]
 [120  50 200]
 [150 160 200]]
Matriz com 10% de desconto:  [[45.   9.  90. ]
 [54.  22.5 90. ]
 [67.5 72.  90. ]]


In [ ]:
# start, end and len array
aleatorio = np.random.randint(1,101,10)
print(aleatorio)

[58 24 88 87 30 68 66 76  8 53]
10


In [58]:
# semente aleatoria
np.random.seed(10)
arr = np.random.randint(1,101,10)
print(arr)

[10 16 65 29 90 94 30  9 74  1]


In [60]:
np.unique(arr)

array([ 1,  9, 10, 16, 29, 30, 65, 74, 90, 94])

In [ ]:
e = np.random.randint(1,10,10)
print(e)
print(np.unique(e, return_counts=True))



[6 6 1 9 4 8 2 6 3 4]
(array([1, 2, 3, 4, 6, 8, 9]), array([1, 1, 1, 2, 3, 1, 1]))
