In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3], dtype=np.int16)
print(arr1)
print(type(arr1))
print(type(arr1[0]))

[1 2 3]
<class 'numpy.ndarray'>
<class 'numpy.int16'>


In [3]:
arr2d = np.array([[-4,2,3],[4,5,6]])
arr2d

array([[-4,  2,  3],
       [ 4,  5,  6]])

In [4]:
print(arr2d.min(), arr2d.argmin())

-4 0


In [5]:
print(arr2d.max(), arr2d.argmax())

6 5


In [6]:
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
# transformar para matriz
zeros_matriz = np.zeros(10).reshape(5,2)
zeros_matriz

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [8]:
a = np.ones([3,3], dtype=np.int16)
b = np.arange(85,101)
print(a)
print(b)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[ 85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100]


In [9]:
c = np.arange(1,10,1)
d = np.arange(9,0,-1)
print(c)
print(d)
print(c + d*2)


[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]
[19 18 17 16 15 14 13 12 11]


In [10]:
print(np.concatenate((c,d)))


[1 2 3 4 5 6 7 8 9 9 8 7 6 5 4 3 2 1]


In [11]:
matriz = np.array([50,10,100,60,25,100,75,80,100]).reshape(3,3) # agua luz net
matriz

array([[ 50,  10, 100],
       [ 60,  25, 100],
       [ 75,  80, 100]])

In [12]:
print("Valor total das contas no mes: ", matriz.sum(1)) 
print("Valor total nos tres meses por tipo: ", matriz.sum(0))
print("Valor gasto de net no período: ", matriz.sum(0)[2])

Valor total das contas no mes:  [160 185 255]
Valor total nos tres meses por tipo:  [185 115 300]
Valor gasto de net no período:  300


In [13]:
# Broadcasting 
print('Matriz dividido por 2: ', matriz/2)
print("Matriz multiplicado por 2: ", matriz*2)
print("Matriz com 10% de desconto: ", matriz * 0.9)

Matriz dividido por 2:  [[25.   5.  50. ]
 [30.  12.5 50. ]
 [37.5 40.  50. ]]
Matriz multiplicado por 2:  [[100  20 200]
 [120  50 200]
 [150 160 200]]
Matriz com 10% de desconto:  [[45.   9.  90. ]
 [54.  22.5 90. ]
 [67.5 72.  90. ]]


In [14]:
# start, end and len array
aleatorio = np.random.randint(1,101,10)
print(aleatorio)

[68 12 62 61  7 40 97 62  2 18]


In [15]:
# semente aleatoria
np.random.seed(10)
arr = np.random.randint(1,101,10)
print(arr)

[10 16 65 29 90 94 30  9 74  1]


In [16]:
np.unique(arr)

array([ 1,  9, 10, 16, 29, 30, 65, 74, 90, 94])

In [17]:
e = np.random.randint(1,10,10)
print(e)
print(np.unique(e, return_counts=True))



[9 7 5 4 1 5 7 9 2 9]
(array([1, 2, 4, 5, 7, 9]), array([1, 1, 1, 2, 2, 3]))


### SLICING EM NUMPY ARRAYS

In [18]:
mtz = np.arange(1,10,1).reshape(3,3)
print(mtz)
print(mtz[2])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[7 8 9]


In [19]:
print(mtz[:,1]) # pegando todas as linhas da segunda coluna
print(mtz[:,1:])

[2 5 8]
[[2 3]
 [5 6]
 [8 9]]


In [20]:
# Condicionais
print(mtz > 5) # template dos itens maiores que 5 TRUE e FALSE
print(mtz[mtz > 5]) # elementos maiores que 5
# print(mtz % 2 == 0)
print(mtz[mtz % 2 == 0]) # elementos pares da matriz

[[False False False]
 [False False  True]
 [ True  True  True]]
[6 7 8 9]
[2 4 6 8]


In [21]:
# Tratamento de textual

arr = np.array(['goku', 'goten', 'gohan', 'trunks', 'bulma'])
print(arr)
print(np.char.find(arr, 'ha')) # retorna o indice da aparição da sequencia de caract = -1 nao tem
print(np.char.find(arr, 'ha') >= 0) # retorna o indice da aparição da sequencia de caract = -1 nao tem
print(arr[np.char.find(arr, 'go') >= 0])

['goku' 'goten' 'gohan' 'trunks' 'bulma']
[-1 -1  2 -1 -1]
[False False  True False False]
['goku' 'goten' 'gohan']


Importando dataset no numpy

In [22]:
ds = np.loadtxt('/home/nkk/Área de trabalho/projetos/C11/space.csv', delimiter=';', dtype=str, encoding='utf-8')
print(ds)

[['\ufeffNum' 'Company Name' 'Location' ... 'Status Rocket' ' Cost'
  'Status Mission']
 ['0' 'SpaceX' 'LC-39A Kennedy Space Center Florida USA' ...
  'StatusActive' '50.0 ' 'Success']
 ['1' 'CASC' 'Site 9401 (SLS-2) Jiuquan Satellite Launch Center China'
  ... 'StatusActive' '29.75 ' 'Success']
 ...
 ['4321' 'US Navy' 'LC-18A Cape Canaveral AFS Florida USA' ...
  'StatusRetired' '0' 'Failure']
 ['4322' 'RVSN USSR' 'Site 1/5 Baikonur Cosmodrome Kazakhstan' ...
  'StatusRetired' '0' 'Success']
 ['4323' 'RVSN USSR' 'Site 1/5 Baikonur Cosmodrome Kazakhstan' ...
  'StatusRetired' '0' 'Success']]


In [23]:
print(ds[0,:])

['\ufeffNum' 'Company Name' 'Location' 'Datum' 'Detail' 'Status Rocket'
 ' Cost' 'Status Mission']


In [24]:
array_cost = ds[1:,6].astype(float)
print(array_cost.mean()) # media dos custos 

34.28669750231268
