In [7]:
import numpy as np

In [3]:
# Exericicio 1
ones = np.ones(8)
aleatorio = np.random.randint(0,10,8)

soma = ones + aleatorio
print(ones)
print(aleatorio)
print(soma)



[1. 1. 1. 1. 1. 1. 1. 1.]
[2 8 6 4 4 9 5 3]
[ 3.  9.  7.  5.  5. 10.  6.  4.]


In [4]:
if sum(soma) >= 40:
    soma = soma.reshape(4,2)
else:
    soma = soma.reshape(2,4)

print(soma)

[[ 3.  9.]
 [ 7.  5.]
 [ 5. 10.]
 [ 6.  4.]]


In [5]:
# Exercicio 2
pares1 = np.arange(0,51,2)
pares2 = np.arange(100,49,-2)

array = np.concatenate((pares1, pares2))
array.sort() # ordenando o array
print(array)



[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  50  52  54  56  58  60  62  64  66  68
  70  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [8]:
# Exercicio 3 - Campo minado
from random import randint
import numpy as np


matriz = np.zeros((2,2))

number_linha = randint(0,1)
number_coluna = randint(0,1)

matriz[number_linha][number_coluna] = 1

print('bomba na posição: ', number_linha, number_coluna)

jogadas = 3
acertos = 0

while jogadas > 0:
    print("Selecione um posição da matriz: ")
    linha = int(input("Entre com a linha ( 0 ou 1): "))
    coluna = int(input("Entre com a coluna ( 0 ou 1): "))
    
    if matriz[linha][coluna] == 0:
        print("Correto acertou uma posição!".center(50,'-'))
        matriz[linha][coluna] = 2 # local descoberto
        
        acertos += 1
        if acertos == 3:
            print("Congratulations! You beat the game!")
            break
        
    elif matriz[linha][coluna] == 2:
        print("posição já escolhida")
        continue
    
    else:
        print("Game Over! :( Try Again! ")
        break   
        
    jogadas -= 1
            
    
    
    
    

bomba na posição:  1 0
Selecione um posição da matriz: 
Game Over! :( Try Again! 


In [ ]:
# Exercicio 4
l = randint(2,6)
c = randint(2,6)
print(l)
print(c)

m = np.random.randint(0,10,(l,c))

print(m)

produto = l * c
print(produto)

if produto % 2 == 0: # valor par é possivel virar um array
    print("Pode virar um array 1D")
else:
    print("Não pode virar um array 1D")
    

6
3
[[1 1 3]
 [9 0 5]
 [0 1 7]
 [8 5 2]
 [3 6 6]
 [4 8 4]]
3
6


In [25]:
# Exercicio 5
# semente aleatoria
np.random.seed(10)
matriz = np.random.randint(1,51, (4,4))
print(matriz)

[[10 37 16  1]
 [50 29 26 30]
 [49 30 50  9]
 [10  1 43 41]]


In [ ]:
media_linha = matriz.mean(axis=1)
media_coluna = matriz.mean(axis=0)
print("Media de cada linha: ", media_linha)
print("Media de cada coluna: ", media_coluna)


Media de cada linha:  [ 64 135 138  95]
Media de cada coluna:  [119  97 135  81]


In [30]:
print("Maior media das linhas: ", media_linha.max())
print("Maior media das colunas: ", media_coluna.max())


Maior media das linhas:  138
Maior media das colunas:  135


In [35]:
numeros_unicos, contagem = np.unique(matriz, return_counts=True)

for number, cont  in zip(numeros_unicos, contagem):
    print(f"O numero {number} aparece {cont}")
    

O numero 1 aparece 2
O numero 9 aparece 1
O numero 10 aparece 2
O numero 16 aparece 1
O numero 26 aparece 1
O numero 29 aparece 1
O numero 30 aparece 2
O numero 37 aparece 1
O numero 41 aparece 1
O numero 43 aparece 1
O numero 49 aparece 1
O numero 50 aparece 2


In [ ]:
# Numeros que aparecem 2 vezes na matriz
print(numeros_unicos[contagem == 2])

[ 1 10 30 50]
