In [62]:
import numpy as np

In [63]:
# Exericicio 1
ones = np.ones(8)
aleatorio = np.random.randint(0,10,8)

soma = ones + aleatorio
print(ones)
print(aleatorio)
print(soma)



[1. 1. 1. 1. 1. 1. 1. 1.]
[1 4 7 6 8 2 6 1]
[2. 5. 8. 7. 9. 3. 7. 2.]


In [64]:
if sum(soma) >= 40:
    soma = soma.reshape(4,2)
else:
    soma = soma.reshape(2,4)

print(soma)

[[2. 5.]
 [8. 7.]
 [9. 3.]
 [7. 2.]]


In [65]:
# Exercicio 2
pares1 = np.arange(0,51,2)
pares2 = np.arange(100,49,-2)

array = np.concatenate((pares1, pares2))
array.sort() # ordenando o array
print(array)



[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  50  52  54  56  58  60  62  64  66  68
  70  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [69]:
# Exercicio 3 - Campo minado
from random import randint
import numpy as np


matriz = np.zeros((2,2))

number_linha = randint(0,1)
number_coluna = randint(0,1)

matriz[number_linha][number_coluna] = 1

print('bomba na posição: ', number_linha, number_coluna)

jogadas = 3
acertos = 0

while jogadas > 0:
    print("Selecione um posição da matriz: ")
    linha = int(input("Entre com a linha ( 0 ou 1): "))
    coluna = int(input("Entre com a coluna ( 0 ou 1): "))
    
    if matriz[linha][coluna] == 0:
        print("Correto acertou uma posição!".center(50,'-'))
        matriz[linha][coluna] = 2 # local descoberto
        
        acertos += 1
        if acertos == 3:
            print("Congratulations! You beat the game!")
            break
        
    elif matriz[linha][coluna] == 2:
        print("posição já escolhida")
        continue
    
    else:
        print("Game Over! :( Try Again! ")
        break   
        
    jogadas -= 1
            
    
    
    
    

bomba na posição:  0 0
Selecione um posição da matriz: 
-----------Correto acertou uma posição!-----------
Selecione um posição da matriz: 
-----------Correto acertou uma posição!-----------
Selecione um posição da matriz: 
Game Over! :( Try Again! 
